<?php
/** @var \Blog\Entity\Post[] $posts */
?>
<h1>Blog</h1>

<h2>Latest Posts</h2>

<?php foreach ($posts as $post): ?>
    <hr/>
    <a href="<?php echo $this->url('post', ['slug' => $post->getSlug()]); ?>">
        <h1><?php echo $this->escapeHtml($post->getTitle()); ?></h1>
    </a>
    <h3><?php echo $this->escapeHtml($post->getWrittenOn()); ?></h3>
    <p><?php echo $this->escapeHtml($post->getPreview()); ?></p>
<?php endforeach; ?>
